version: "3"
services:
  file-storage:
    restart: always
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    container_name: s3-file-storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Password1234
      MINIO_SERVER_URL: "http://localhost:9000"
    command: server --console-address ":9001" /file-storage-volume
    volumes:
      - file-storage-volume:/file-storage-volume
    ports:
      - 9000:9000 # Files will be served via this port
      - 9001:9001 # Admin console can be access via this port

volumes:
  file-storage-volume:
